<?php

define(
    'SCC_HELPDESK_LINKS',
    [
        'helpdesk-home'                           => 'https://help.stylishcostcalculator.com/en/',
        'helpdesk-troubleshooting'                => 'https://help.stylishcostcalculator.com/en/category/troubleshooting-h24f3p/',
        'helpdesk-video-tutorials'                => 'https://help.stylishcostcalculator.com/en/category/video-tutorials-1wlpjut/',
        'helpdesk-features'                       => 'https://help.stylishcostcalculator.com/en/category/features-22x2mc/',
        'element-distance-cost'                   => 'https://help.stylishcostcalculator.com/en/article/element-distance-based-cost-1krd3ir/',
        'element-dropdown'                        => 'https://help.stylishcostcalculator.com/en/article/element-dropdown-menu-1z0zkha/',
        'element-signature-box'                   => 'https://help.stylishcostcalculator.com/en/article/element-signature-box-1xv0y3e/',
        'element-slider'                          => 'https://help.stylishcostcalculator.com/en/article/element-slider-1pim5ug/',
        'element-checkbox'                        => 'https://help.stylishcostcalculator.com/en/article/element-checkbox-toggle-switches-simple-buttons-fiy5v7/',
        'element-image-buttons'                   => 'https://help.stylishcostcalculator.com/en/article/element-image-buttons-15nwxur/',
        'element-quantity-input-box'              => 'https://help.stylishcostcalculator.com/en/article/element-quantity-input-box-nxgayn/',
        'element-custom-math'                     => 'https://help.stylishcostcalculator.com/en/article/element-custom-math-1jqqu40/',
        'element-variable-math'                   => 'https://help.stylishcostcalculator.com/en/article/element-variable-math-1sydr0m/',
        'element-file-upload'                     => 'https://help.stylishcostcalculator.com/en/article/element-file-upload-1fjq4it/',
        'element-date-picker'                     => 'https://help.stylishcostcalculator.com/en/article/element-date-picker-8006b4/',
        'element-text-html-field'                 => 'https://help.stylishcostcalculator.com/en/article/element-texthtml-field-vzqdna/',
        'element-comment-box'                     => 'https://help.stylishcostcalculator.com/en/article/element-comment-box-ha9v2m/',
        'element-slider-all-types'                => 'https://help.stylishcostcalculator.com/en/article/slider-modes-bulk-quantity-pricing-discounts-and-sliding-scale-pricing-8228xo/',
        'element-enable-price-hint-bubble'        => 'https://help.stylishcostcalculator.com/en/article/price-hint-learn-more-about-this-feature-1jccpbz/',
        'element-slider-show-user-savings'        => 'https://help.stylishcostcalculator.com/en/article/show-user-savings-how-to-visualize-savings-to-your-customers-1viforv/',
        'feature-frontend-tooltip'                => 'https://help.stylishcostcalculator.com/en/article/frontend-tool-tips-add-clarity-guide-your-customers-through-your-services-h06xgx/',
        'feature-price-rounding'                  => 'https://help.stylishcostcalculator.com/en/article/price-rounding-a-complete-guide-1ncp6ik/',
        'feature-blur-total-price'                => 'https://help.stylishcostcalculator.com/en/article/hide-or-blur-total-price-for-lead-generation-1g9v38y/',
        'feature-element-style-skin'              => 'https://help.stylishcostcalculator.com/en/article/frontend-styles-frontend-skins-kfaq29/',
        'feature-multi-step-form'                 => 'https://help.stylishcostcalculator.com/en/article/multi-step-forms-a-complete-guide-1xcoyhe/',
        'feature-show-unit-price'                 => 'https://help.stylishcostcalculator.com/en/article/per-unit-price-a-complete-guide-for-the-global-per-unit-cost-18u04mo/',
        'feature-minimum-total-price'             => 'https://help.stylishcostcalculator.com/en/article/mandatory-minimum-total-a-complete-guide-1f666ye/',
        'feature-total-price-range-settings'      => 'https://help.stylishcostcalculator.com/en/article/price-range-a-complete-guide-1qnqpod/',
        'feature-show-unit-price-column'          => 'https://help.stylishcostcalculator.com/en/article/concealing-the-unit-price-a-simple-guide-1alp80q/',
        'feature-show-quantity-column'            => 'https://help.stylishcostcalculator.com/en/article/hide-quantity-how-do-i-do-this-1ax845j/',
        'feature-show-search-box'                 => 'https://help.stylishcostcalculator.com/en/article/search-box-a-complete-guide-1z12mz7/',
        'feature-live-currency-conversion'        => 'https://help.stylishcostcalculator.com/en/article/live-currency-conversion-a-complete-guide-188nhpy/',
        'feature-webhooks'                        => 'https://help.stylishcostcalculator.com/en/article/webhooks-a-complete-guide-6dauur/',
        'feature-custom-events'                   => 'https://help.stylishcostcalculator.com/en/article/custom-events-trigger-js-code-a-complete-guide-bwwykw/',
        'feature-payment-option-paypal'           => 'https://help.stylishcostcalculator.com/en/article/paypal-integration-a-complete-guide-mi7e45/',
        'feature-payment-option-stripe'           => 'https://help.stylishcostcalculator.com/en/article/stripe-integration-everything-to-know-al2492/',
        'feature-stripe-subscriptions'            => 'https://help.stylishcostcalculator.com/en/article/stripe-subscriptions-a-complete-guide-325hot/',
        'feature-require-acceptance'              => 'https://help.stylishcostcalculator.com/en/article/acceptance-box-a-complete-guide-1e2ilkc/',
        'feature-twilio-console'                  => 'https://www.twilio.com/console',
        'element-mandatory-elements'              => 'https://help.stylishcostcalculator.com/en/article/required-fields-a-complete-guide-175ii48/',
        'feature-conditional-logic'               => 'https://help.stylishcostcalculator.com/en/article/conditional-logic-a-complete-guide-1nlqkzj/',
        'feature-woocommerce-integration'         => 'https://help.stylishcostcalculator.com/en/article/woocommerce-integration-a-complete-guide-19esndu/',
        'feature-email-validator'                 => 'https://help.stylishcostcalculator.com/en/article/email-validator-the-ultimate-guide-f7sgf/',
        'feature-email-quote-form'                => 'https://help.stylishcostcalculator.com/en/article/email-quote-form-a-complete-guide-5ygk4m/',
        'feature-sms-quote'                       => 'https://help.stylishcostcalculator.com/en/article/sms-quotes-a-complete-guide-1j5kz01/',
        'feature-customizing-style'               => 'https://help.stylishcostcalculator.com/en/article/customizing-the-style-of-the-calculator-form-7m2b7g/',
        'feature-integrations'                    => 'https://help.stylishcostcalculator.com/en/article/integrations-how-to-integrate-with-zapier-integromat-pabbly-automatioio-and-more-19yol2i/',
        'feature-custom-totals'                   => 'https://help.stylishcostcalculator.com/en/article/custom-totals-a-complete-guide-mt1z0l/',
        'feature-leads-quotes-management'         => 'https://help.stylishcostcalculator.com/en/article/leads-quotes-management-system-a-complete-guide-169932m/',
        'feature-coupon-code'                     => 'https://help.stylishcostcalculator.com/en/article/coupon-code-everything-to-know-about-this-feature-828rgp/',
        'feature-form-conversion-analytics'       => 'https://help.stylishcostcalculator.com/en/article/form-conversion-analytics-a-complete-guide-1ffunxs/',
        'feature-lead-source-analytics'           => 'https://help.stylishcostcalculator.com/en/article/lead-source-analytics-a-complete-guide-tmjp95/',
        'feature-floating-itemized-list'          => 'https://help.stylishcostcalculator.com/en/article/floating-itemized-list-detailed-list-view-a-complete-guide-1uo2ivm/',
        'feature-itemized-pdf'                    => 'https://help.stylishcostcalculator.com/en/article/itemized-pdf-a-complete-guide-for-the-generated-pdf-quotes-and-email-quotes-12f5prz/',
        'feature-span-captcha'                    => 'https://help.stylishcostcalculator.com/en/article/spam-honeypot-google-captcha-how-do-i-deal-with-spam-coming-through-the-form-je9m7p/',
        'feature-payment-options'                 => 'https://help.stylishcostcalculator.com/en/article/e-commerce-payments-personalize-the-checkout-experience-for-woocommerce-stripe-and-paypal-1dbuj5l/',
        'tutorial-conditional-alerts'             => 'https://help.stylishcostcalculator.com/en/article/implementing-context-specific-alerts-your-step-by-step-guide-to-conditional-banners-and-messages-1o2pk53/',
        'tutorial-implementing-base-fee'          => 'https://help.stylishcostcalculator.com/en/article/implementing-base-fees-adding-mandatory-charges-in-your-calculator-form-1ejv986/',
        'tutorial-custom-percentage-addition'     => 'https://help.stylishcostcalculator.com/en/article/custom-percentage-addition-is-it-possible-to-include-a-custom-percentage-in-the-calculator-rgyb96/',
        'tutorial-master-guide-trigger-fee'       => 'https://help.stylishcostcalculator.com/en/article/master-guide-trigger-a-charge-fee-or-discount-1szobaq/',
        'tutorial-customer-contact-detail'        => 'https://help.stylishcostcalculator.com/en/article/customer-contact-details-how-do-i-build-my-calculator-to-request-their-name-address-ect-syllys/',
        'tutorial-remove-coupon-detailed-list'    => 'https://help.stylishcostcalculator.com/en/article/coupon-detailed-list-buttons-how-do-i-remove-them-17mpbkq/',
        'tutorial-customize-email-quote-msg'      => 'https://help.stylishcostcalculator.com/en/article/customize-the-email-quote-message-at-the-calculator-level-1tligfu/',
        'use-case-lead-generation'                => 'https://help.stylishcostcalculator.com/en/article/lead-generation-force-users-to-give-their-details-email-before-seeing-the-price-np8c1l/',
        'use-case-donation-pay-invoice'           => 'https://help.stylishcostcalculator.com/en/article/donation-pay-invoice-allow-users-to-pick-a-price-for-the-cart-total-l5l2tt/',
        'use-case-self-generating-quotes'         => 'https://help.stylishcostcalculator.com/en/article/self-generating-quotes-automate-estimates-for-your-business-cl6uvw/',
        'use-case-product-configurator'           => 'https://help.stylishcostcalculator.com/en/article/product-recommender-guide-customers-to-the-perfect-product-xvcqm/',
        'use-case-product-recommender-quiz'       => 'https://help.stylishcostcalculator.com/en/article/product-recommender-quiz-customize-offerings-for-varied-industries-1bqpfsw/',
        'use-case-pricing-table'                  => 'https://help.stylishcostcalculator.com/en/article/dynamic-pricing-table-add-a-customizable-componet-to-your-pricing-table-yttbw/',
        'use-case-internal-tool'                  => 'https://help.stylishcostcalculator.com/en/article/internal-tool-empower-your-sales-team-to-provide-accurate-quotes-1ymgq9u/',
        'faq-what-are-dmark-spf-dkim'             => 'https://help.stylishcostcalculator.com/en/article/what-are-dmarc-spf-and-dkim-13suvfh/',
        'faq-collect-customer-information'        => 'https://help.stylishcostcalculator.com/en/article/collect-customer-information-how-can-i-force-the-user-to-give-an-email-before-seeing-the-price-1nafjs4/',
        'faq-display-or-hide-items'               => 'https://help.stylishcostcalculator.com/en/article/no-cost-items-how-do-i-display-or-hide-these-items-1djyte7/',
        'troubleshoot-email-setup'                => 'https://help.stylishcostcalculator.com/en/article/email-setup-troubleshoot-sending-quotes-by-email-smtp-server-p4z86i/',
        'troubleshoot-cache-plugins'              => 'https://help.stylishcostcalculator.com/en/article/important-cache-plugin-setup-your-cache-plugin-list-of-supported-cache-plugins-xi924e/',
        'troubleshoot-email-pdf'                  => 'https://help.stylishcostcalculator.com/en/article/email-pdf-troubleshooting-issues-with-the-email-quote-and-pdf-generator-6vv0ze/',
        'troubleshoot-embedding-to-webpage'       => 'https://help.stylishcostcalculator.com/en/article/embedding-to-your-webpage-deploying-and-adding-the-shortcode-calculator-form-to-your-page-g2ynny/',
        'troubleshoot-woocommerce-bulk-pricing'   => 'https://help.stylishcostcalculator.com/en/article/woocommerce-bulk-pricing-discounts-sliding-scale-pricing-1st0v51/',
        'troubleshoot-transfer-my-license'        => 'https://help.stylishcostcalculator.com/en/article/scc-license-how-do-i-transfer-my-license-to-another-site-migrating-to-a-new-domain-1ijwyt1/',
        'troubleshoot-members-portal-change-info' => 'https://help.stylishcostcalculator.com/en/article/members-portal-how-do-i-change-my-email-address-or-payment-method-1jtzz16/',
        'troubleshoot-wp-memory-limit'            => 'https://help.stylishcostcalculator.com/en/article/wp-memory-limit-or-the-email-quote-gets-stuck-at-90-15ndy53/',
        'tutorial-slider-sections-subsections'    => 'https://help.stylishcostcalculator.com/en/article/important-understanding-the-math-of-a-slider-sections-vs-subsections-1c10sjj/',
        ]
);

define(
    'SCC_ELEMENT_TYPES',
    [
        'Dropdown Menu' => 'dropdown-element',
        'checkbox'      => 'checkbox-element',
        'comment box'   => 'comment-box-element',
        'quantity box'  => 'quantity-box-element',
        'custom math'   => 'custom-math-element',
        'file upload'   => 'file-upload-element',
        'texthtml'      => 'texthtml-element',
        'slider'        => 'slider-element',
        'math'          => 'variable-math-element',
        'date'          => 'date-picker-element',
        'distance'      => 'distance-element',
    ]
);

define(
    'QUOTES_MANAGEMENT_PAGE_TABLE_ALL_COLUMNS',
    [
        'displayIpBrowserColumn' => 'true',
        'showInTable'            => [
            0 => [
                'name' => [
                    'name' => 'Your Name',
                ],
            ],
            1 => [
                'email' => [
                    'name' => 'Your Email',
                ],
            ],
            2 => [
                'phone' => [
                    'name' => 'Your Phone',
                ],
            ],
            3 => [
                'referer' => [
                    'name' => 'Referring Page',
                ],
            ],
            4 => [
                'traffic_source' => [
                    'name' => 'Traffic source',
                ],
            ],
            5 => [
                'traffic_medium' => [
                    'name' => 'Traffic medium',
                ],
            ],
            6 => [
                'calc_total' => [
                    'name' => 'Total',
                ],
            ],
            7 => [
                'calc_name' => [
                    'name' => 'Calc Name',
                ],
            ],
            8 => [
                'first_page' => [
                    'name' => 'First Page',
                ],
            ],
        ],
    ]
);

define( 'DF_SCC_QUIZ_CHOICES', [
    'step1'              => [
        [
            'choiceTitle' => 'Product',
            'icon'        => 'package',
            'key'         => 'product',
        ],
        [
            'choiceTitle' => 'Service',
            'icon'        => 'tool',
            'key'         => 'service',
        ],
        [
            'choiceTitle' => 'Both',
            'icon'        => [
                0 => 'tool',
                1 => 'package',
            ],
            'key'         => 'both',
        ],
    ],
    'step2'              => [
        [
            'choiceTitle'       => 'Straight Forward',
            'choiceDescription' => 'simple pricing: 1 Item costs $10 each',
            'key'               => 'straight-forward',
            'icon'				          => 'arrow_forward',
            'helpLink'          => '#',
        ],
        [
            'choiceTitle'       => 'Bulk Pricing',
            'choiceDescription' => 'I give discounts to customers who buy in bulk (10 or more items)',
            'key'               => 'bulk-pricing',
            'icon'              => 'local_offer',
            'helpLink'          => SCC_HELPDESK_LINKS['element-slider-show-user-savings'],
        ],
        [
            'choiceTitle'       => 'Mandatory Fees',
            'choiceDescription' => 'like setup fees, admin fees, shipping fees, etc',
            'key'               => 'mandatory-fees',
            'icon'				          => 'error_outline',
            'helpLink'          => SCC_HELPDESK_LINKS['tutorial-implementing-base-fee'],
        ],
        [
            'choiceTitle'       => 'Need Complex Pricing',
            'choiceDescription' => '((Item 1 + Item 2) x 12) / 12 or (Length X Width X Height)',
            'key'               => 'need-complex-math',
            'icon'				          => 'functions',
            'helpLink'          => SCC_HELPDESK_LINKS['element-variable-math'],
        ],
        [
            'choiceTitle'       => 'Need To Apply A Percentage',
            'choiceDescription' => 'I need to take a section total and add 20% to it.',
            'key'               => 'need-to-apply-a-percentage',
            'icon'              => 'percent',
            'helpLink'          => SCC_HELPDESK_LINKS['tutorial-custom-percentage-addition'],
        ],
        [
            'choiceTitle'       => 'Need To Trigger A Fee Or Discount',
            'choiceDescription' => 'under certain situations, I want to trigger a fee of 20%',
            'key'               => 'need-to-trigger-a-fee-or-discount',
            'icon'              => 'money_off',
            'helpLink'          => SCC_HELPDESK_LINKS['tutorial-master-guide-trigger-fee'],
        ],
        [
            'choiceTitle'       => 'Other',
            'choiceDescription' => 'I need something else',
            'key'               => 'others',
            'icon'              => 'more_horiz',
            'helpLink'          => '#',
        ],
    ],
    'step3'              => [
        [
            'choiceTitle'       => 'Lead Generation',
            'choiceDescription' => 'Users need to enter their contact to get the final price',
            'key'               => 'lead-gen-user-enters-contact-to-see-final-price',
            'icon'              => 'person_add',
            'helpLink'          => SCC_HELPDESK_LINKS['use-case-lead-generation'],
        ],
        [
            'choiceTitle'       => 'E-Commerce',
            'choiceDescription' => 'I want to sell my products/services with Stripe, PayPal or WooCommerce',
            'key'               => 'e-comm',
            'icon'              => 'shopping_cart',
            'helpLink'          => SCC_HELPDESK_LINKS['feature-payment-options'],
        ],
        [
            'choiceTitle'       => 'Product Recommender',
            'choiceDescription' => 'Guide Customers to the Perfect Product',
            'key'               => 'product-recommender',
            'icon'              => 'quiz',
            'helpLink'          => SCC_HELPDESK_LINKS['use-case-product-recommender-quiz'],
        ],
        [
            'choiceTitle'       => 'Internal Tool',
            'choiceDescription' => 'I want my sales staff to use this tool to quote prospects',
            'key'               => 'internal-tool',
            'icon'              => 'build',
            'helpLink'          => SCC_HELPDESK_LINKS['use-case-internal-tool'],
        ],
        [
            'choiceTitle'       => 'Pricing Table',
            'choiceDescription' => "Three podiums with 'Bronze', 'Silver', and 'Gold' labels",
            'key'               => 'pricing-table',
            'icon'              => 'view_week',
            'helpLink'          => SCC_HELPDESK_LINKS['use-case-pricing-table'],
        ],
        [
            'choiceTitle'       => 'Donation / Pay Invoice',
            'choiceDescription' => 'For donations, paying invoice, more',
            'key'               => 'user-defied-pricing',
            'icon'              => 'payments',
            'helpLink'          => SCC_HELPDESK_LINKS['use-case-donation-pay-invoice'],
        ],
        [
            'choiceTitle'       => 'Sending Quotes',
            'choiceDescription' => 'I want to send customer\'s Quotes via Email (PDF)',
            'key'               => 'send-email-quotes-pdf',
            'icon'              => 'format_quote',
            'helpLink'          => SCC_HELPDESK_LINKS['use-case-self-generating-quotes'],
        ],
        [
            'choiceTitle'       => 'Product Configurator',
            'choiceDescription' => 'I have products that need customizing and have add-on options',
            'key'               => 'prod-config',
            'icon'              => 'tune',
            'helpLink'          => SCC_HELPDESK_LINKS['use-case-product-configurator'],
        ],
        [
            'choiceTitle'       => 'Other',
            'choiceDescription' => 'I need something else',
            'key'               => 'others',
            'icon'              => 'more_horiz',
            'helpLink'          => '#',
        ],
    ],
    'step4'              => [
        [
            'choiceTitle'       => 'Conditional Logic',
            'choiceDescription' => 'I need to only show certain items at certain times or conditions',
            'key'               => 'conditional-logic',
            'icon'              => 'filter_list',
            'helpLink'          => SCC_HELPDESK_LINKS['feature-conditional-logic'],
        ],
        [
            'choiceTitle'       => 'SMS',
            'choiceDescription' => 'Send customer quotes vis SMS (and two-way messaging app)',
            'key'               => 'lead-gen-two-way-sms',
            'icon'              => 'sms',
            'helpLink'          => SCC_HELPDESK_LINKS['feature-sms-quote'],
        ],
        [
            'choiceTitle'       => 'Multi-Step',
            'choiceDescription' => 'I want to make my form clean and organized with a multi-step process',
            'key'               => 'multi-step',
            'icon'              => 'format_list_numbered',
            'helpLink'          => SCC_HELPDESK_LINKS['feature-multi-step-form'],
        ],
        [
            'choiceTitle'       => 'International Customers',
            'choiceDescription' => 'I want to display the cost in the currency of my international user\'s country',
            'key'               => 'international-customers',
            'icon'              => 'language',
            'helpLink'          => SCC_HELPDESK_LINKS['feature-live-currency-conversion'],
        ],
        [
            'choiceTitle'       => 'Automation',
            'choiceDescription' => 'I want to use API and Webhooks to connect my calculator form to other tools',
            'key'               => 'automation',
            'icon'              => 'settings_input_component',
            'helpLink'          => SCC_HELPDESK_LINKS['feature-integrations'],
        ],
        [
            'choiceTitle'       => 'Competitor Comparison',
            'choiceDescription' => 'I want to compare my prices to my competitors',
            'key'               => 'competitor-comparison',
            'icon'              => 'compare',
            'helpLink'          => SCC_HELPDESK_LINKS['feature-custom-totals'],
        ],
        [
            'choiceTitle'       => 'Lead Management',
            'choiceDescription' => 'I want a screen to see all my leads, where they came from, and keep track of the lead status (won, lost, in-negotiation)',
            'key'               => 'lead-management',
            'icon'              => 'assignment',
            'helpLink'          => SCC_HELPDESK_LINKS['feature-leads-quotes-management'],
        ],
        [
            'choiceTitle'       => 'Stylish',
            'choiceDescription' => 'I want my calculator lead form to look attractive for my users to interact with it and focus on the calls-to-actions',
            'key'               => 'stylish',
            'icon'              => 'style',
            'helpLink'          => SCC_HELPDESK_LINKS['feature-customizing-style'],
        ],
        [
            'choiceTitle'       => 'Coupons',
            'choiceDescription' => 'I want a coupon system to encourage prospects to buy now.',
            'key'               => 'coupons',
            'icon'              => 'card_giftcard',
            'helpLink'          => SCC_HELPDESK_LINKS['feature-coupon-code'],
        ],
        [
            'choiceTitle'       => 'Other',
            'choiceDescription' => 'I need something else',
            'key'               => 'others',
            'icon'              => 'more_horiz',
            'helpLink'          => '#',
        ],
    ],
    'step5'              => [
        [
            'choiceTitle'       => 'Stats & Conversion Tracking',
            'choiceDescription' => 'I want to track where my orders, quotes, and leads come from.',
            'key'               => 'stats-n-conversion-tracking',
            'icon'              => 'show_chart',
            'helpLink'          => SCC_HELPDESK_LINKS['feature-form-conversion-analytics'],
        ],
        [
            'choiceTitle'       => 'Analytics',
            'choiceDescription' => 'I want AI analytics to help me identify trends and anomalies',
            'key'               => 'analytical-ai',
            'icon'              => 'analytics',
            'helpLink'          => SCC_HELPDESK_LINKS['feature-lead-source-analytics'],
        ],
        [
            'choiceTitle'       => 'Minimum Total',
            'choiceDescription' => 'I need feature to encourage the purchase of a minimum total',
            'key'               => 'set-minimum-total',
            'icon'              => 'attach_money',
            'helpLink'          => SCC_HELPDESK_LINKS['feature-minimum-total-price'],
        ],
        [
            'choiceTitle'       => 'Distanced-Based Cost',
            'choiceDescription' => 'Allows users to calculate the cost of a product or service based on the distance between two locations using Google Maps API. Idea if you need to incorporate travel or delivery costs into their pricing models.',
            'key'               => 'shipping-rates-calculator',
            'icon'              => 'local_shipping',
            'helpLink'          => SCC_HELPDESK_LINKS['element-distance-cost'],
        ],
        [
            'choiceTitle'       => 'Upsells & Cross Sells',
            'choiceDescription' => 'I want to encourage users to select a related service or add-on',
            'key'               => 'upsells-n-cross-sales',
            'icon'              => 'shopping_basket',
            'helpLink'          => SCC_HELPDESK_LINKS['feature-blur-total-price'],
        ],
        [
            'choiceTitle'       => 'Add Clarity, Credibility and Reduce Friction',
            'choiceDescription' => '',
            'key'               => 'add-clarity-credibility-reduce-friction',
            'icon'              => 'verified',
            'helpLink'          => SCC_HELPDESK_LINKS['feature-frontend-tooltip'],
        ],
        [
            'choiceTitle'       => 'File Uploads',
            'choiceDescription' => 'I need the user to upload images, PDF or any files',
            'key'               => 'file-uploads',
            'icon'              => 'file_upload',
            'helpLink'          => SCC_HELPDESK_LINKS['element-file-upload'],
        ],
        [
            'choiceTitle'       => 'Date Picker',
            'choiceDescription' => 'I want my users to be able to select a date of service',
            'key'               => 'date-picker',
            'icon'              => 'date_range',
            'helpLink'          => SCC_HELPDESK_LINKS['element-date-picker'],
        ],
        [
            'choiceTitle'       => 'User Inputs',
            'choiceDescription' => 'I need to ask my users some questions to understand their needs better',
            'key'               => 'user-inputs',
            'icon'              => 'input',
            'helpLink'          => SCC_HELPDESK_LINKS['tutorial-customer-contact-detail'],
        ],
        [
            'choiceTitle'       => 'Conditional Messages & Alerts',
            'choiceDescription' => 'I need to draw attention to specific information based on predefined conditions. For instance, when a user selects a particular service, an alert is triggered to provide important information.',
            'key'               => 'conditional-messages-n-alerts',
            'icon'              => 'notification_important',
            'helpLink'          => SCC_HELPDESK_LINKS['tutorial-conditional-alerts'],
        ],
        [
            'choiceTitle'       => 'Other',
            'choiceDescription' => 'I need something else',
            'key'               => 'others',
            'icon'              => 'more_horiz',
            'helpLink'          => '#',
        ],
    ],
    'stepResult'         => [
        [
            'choiceTitle'               => 'Conditional Logic',
            'instructionText'           => 'Add A Conditional Logic',
            'icon'                      => 'git-pull-request',
            'helpLink'                  => SCC_HELPDESK_LINKS['feature-conditional-logic'],
            'key'                       => 'conditional-logic',
            'evaluateAsDoneConditions'  => [ 'calculator.has_conditional_logic' ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'Bulk Discounts',
            'instructionText'           => 'Create A Bulk Discount',
            'icon'                      => 'hash',
            'helpLink'                  => SCC_HELPDESK_LINKS['element-slider-show-user-savings'],
            'key'                       => 'bulk-discounts',
            'evaluateAsDoneConditions'  => [ 'calculator.has_slider_with_bulk_mode' ],
            'requiresPremium'           => false,
        ],
        [
            'choiceTitle'               => 'PayPal',
            'instructionText'           => 'Add PayPal Checkout',
            'icon'                      => 'paypal',
            'isDetectable'              => false,
            'helpLink'                  => SCC_HELPDESK_LINKS['feature-payment-option-paypal'],
            'key'                       => 'paypal',
            'evaluateAsDoneConditions'  => [ 'calculator.has_paypal_enabled' ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'SMS Quotes',
            'instructionText'           => 'Use SMS Quotes',
            'icon'                      => 'sms',
            'helpLink'                  => SCC_HELPDESK_LINKS['feature-sms-quote'],
            'key'                       => 'sms-feature',
            'isDetectable'              => false,
            'evaluateAsDoneConditions'  => [ [ 'global.has_sms_enabled', 'calculator.has_sms_enabled' ], 'global.has_visited_sms_page' ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'Stripe',
            'instructionText'           => 'Add Stripe Checkout',
            'icon'                      => 'stripe',
            'isDetectable'              => false,
            'helpLink'                  => SCC_HELPDESK_LINKS['feature-stripe-subscriptions'],
            'key'                       => 'stripe',
            'evaluateAsDoneConditions'  => [ 'calculator.stripe_enabled' ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'Woocommerce',
            'instructionText'           => 'Enable WooCommerce Integration',
            'icon'                      => 'hash',
            'helpLink'                  => SCC_HELPDESK_LINKS['feature-woocommerce-integration'],
            'key'                       => 'woocommerce',
            'isDetectable'              => false,
            'evaluateAsDoneConditions'  => [ 'calculator.woocommerce_enabled' ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'Total Price',
            'instructionText'           => 'Hide or Blur Total Price for Lead Generation',
            'icon'                      => 'hash',
            'helpLink'                  => SCC_HELPDESK_LINKS['feature-blur-total-price'],
            'key'                       => 'total-price',
            'evaluateAsDoneConditions'  => [ 'calculator.total_price_blur_or_hide' ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'Turn Off the Total Price',
            'instructionText'           => 'Hide the total price, or blur the total price (if blurred, reveals when quote form is filled up)',
            'icon'                      => 'hash',
            'helpLink'                  => SCC_HELPDESK_LINKS['faq-collect-customer-information'],
            'key'                       => 'turn-off-total-price',
            'evaluateAsDoneConditions'  => [ [ 'calculator.hide_total_price', 'calculator.blur_total_price' ] ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'Email Quote Button as Primary CTA, other buttons a secondary button',
            'instructionText'           => 'Setup Email Quote Button as Primary CTA, other buttons a secondary button',
            'choiceSimpleTitle'         => 'Email Quote Button as Primary CTA',
            'icon'                      => 'hash',
            'helpLink'                  => SCC_HELPDESK_LINKS['feature-email-quote-form'],
            'key'                       => 'email-quote-primary-cta',
            'showSuggestion'            => false,
            'evaluateAsDoneConditions'  => [ 'calculator.email-quote-primary-cta' ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'Customize Outgoing Email',
            'instructionText'           => 'Customize Outgoing Email',
            'icon'                      => 'hash',
            'helpLink'                  => SCC_HELPDESK_LINKS['tutorial-customize-email-quote-msg'],
            'key'                       => 'email-quote-custom-outgoing-message',
            'showSuggestion'            => false,
            'evaluateAsDoneConditions'  => [ 'calculator.email-quote-primary-cta' ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'Zapier/Webhooks',
            'instructionText'           => 'Setup Webhooks or Zapier',
            'icon'                      => 'hash',
            'helpLink'                  => SCC_HELPDESK_LINKS['feature-webhooks'],
            'key'                       => 'use-webhooks',
            'isDetectable'              => false,
            'evaluateAsDoneConditions'  => [ [ 'calculator.zapier_enabled', 'calculator.webhook_enabled' ] ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'Multi Step Feature',
            'instructionText'           => 'Enable Multi Step Feature',
            'icon'                      => 'hash',
            'helpLink'                  => SCC_HELPDESK_LINKS['feature-multi-step-form'],
            'key'                       => 'use-multi-step',
            // 'evaluateAsDoneConditions'  => [ 'calculator.multi_step_enabled' ],
        ],
        [
            'choiceTitle'               => 'Live Currency Conversion',
            'instructionText'           => 'Setup Live Currency Conversion',
            'icon'                      => 'hash',
            'helpLink'                  => SCC_HELPDESK_LINKS['feature-live-currency-conversion'],
            'key'                       => 'use-live-currency-conversion',
            'evaluateAsDoneConditions'  => [ 'calculator.currency_conversion_enabled' ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'Custom Totals',
            'instructionText'           => 'Apply Custom Totals',
            'icon'                      => 'hash',
            'helpLink'                  => SCC_HELPDESK_LINKS['feature-custom-totals'],
            'key'                       => 'use-custom-totals',
            'isDetectable'              => false,
            'evaluateAsDoneConditions'  => [ 'calculator.no_method_to_detect' ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'Quote Management Screen',
            'instructionText'           => 'Use Quote Management Feature',
            'icon'                      => 'hash',
            'helpLink'                  => SCC_HELPDESK_LINKS['feature-leads-quotes-management'],
            'key'                       => 'use-quote-management-screen',
            'showSuggestion'            => false,
            'evaluateAsDoneConditions'  => [ 'calculator.visited_quote_management_screen' ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'Coupon Code',
            'instructionText'           => 'Use Coupon Code Button',
            'icon'                      => 'hash',
            'helpLink'                  => SCC_HELPDESK_LINKS['feature-coupon-code'],
            'key'                       => 'use-coupon-code-btn',
            'isDetectable'              => false,
            'evaluateAsDoneConditions'  => [ 'calculator.coupon_code_button_enabled', 'global.has_coupon_codes' ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'Cost Per Unit',
            'instructionText'           => 'Show a Cost Per Unit Summary',
            'icon'                      => 'hash',
            'helpLink'                  => SCC_HELPDESK_LINKS['feature-show-unit-price'],
            'key'                       => 'use-cost-per-unit',
            'evaluateAsDoneConditions'  => [ 'calculator.cost_per_unit_enabled' ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'Custom Event Triggers',
            'instructionText'           => 'Add JavaScript Event Triggers',
            'icon'                      => 'hash',
            'helpLink'                  => SCC_HELPDESK_LINKS['feature-custom-events'],
            'key'                       => 'use-custom-event-triggers',
            'evaluateAsDoneConditions'  => [ 'calculator.has_custom_js_callbacks_on_events' ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'Minimum Total',
            'instructionText'           => 'Apply a Minimum Total',
            'icon'                      => 'hash',
            'helpLink'                  => SCC_HELPDESK_LINKS['feature-minimum-total-price'],
            'key'                       => 'use-minimum-total-feature',
            'evaluateAsDoneConditions'  => [ 'calculator.minimum_total_enabled' ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'Conditional Logic with Text Elements',
            'instructionText'           => 'Use Conditional Logic with Text Elements',
            'choiceSimpleTitle'         => 'Conditional Logic',
            'icon'                      => 'hash',
            'helpLink'                  => SCC_HELPDESK_LINKS['tutorial-conditional-alerts'],
            'key'                       => 'use-cl-with-txt-elements',
            'evaluateAsDoneConditions'  => [ 'calculator.text_element_with_conditional_logic' ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'Fontend Tool-Tips',
            'instructionText'           => 'Add Fontend Tool-Tips',
            'icon'                      => 'hash',
            'helpLink'                  => SCC_HELPDESK_LINKS['feature-frontend-tooltip'],
            'key'                       => 'use-frontend-tooltips',
            'evaluateAsDoneConditions'  => [ 'calculator.frontend_tooltip_enabled' ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'Price Hint',
            'instructionText'           => 'Show a Price Bubble Hint',
            'icon'                      => 'hash',
            'helpLink'                  => SCC_HELPDESK_LINKS['element-enable-price-hint-bubble'],
            'key'                       => 'use-price-hint',
            'evaluateAsDoneConditions'  => [ 'calculator.price_hint_used' ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'Email Validator',
            'instructionText'           => 'Enable Email Validator',
            'icon'                      => 'hash',
            'helpLink'                  => SCC_HELPDESK_LINKS['feature-email-validator'],
            'key'                       => 'use-email-validator',
            'evaluateAsDoneConditions'  => [ 'global.validate_email_feature_enabled' ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'Detailed List',
            'instructionText'           => 'Show a Detailed List',
            'icon'                      => 'list',
            'isDetectable'              => false,
            'helpLink'                  => SCC_HELPDESK_LINKS['feature-floating-itemized-list'],
            'key'                       => 'detailed-list',
            'evaluateAsDoneConditions'  => [ 'calculator.detailed_list_btn_enabled' ],
            'requiresPremium'           => false,
        ],
        [
            'choiceTitle'               => 'Turn Off the Detailed List',
            'instructionText'           => 'Remove the Detailed List Button',
            'icon'                      => 'list',
            'helpLink'                  => SCC_HELPDESK_LINKS['tutorial-remove-coupon-detailed-list'],
            'key'                       => 'turn-off-detailed-list',
            'evaluateAsDoneConditions'  => [ 'calculator.detailed_list_btn_disabled' ],
            'requiresPremium'           => false,
        ],
        [
            'choiceTitle'               => 'Activate Accordion',
            'instructionText'           => 'Use the Accordion Feature',
            'icon'                      => 'list',
            'helpLink'                  => '#',
            'key'                       => 'activate-accordion',
            'evaluateAsDoneConditions'  => [ 'calculator.accordion_enabled' ],
            'requiresPremium'           => false,
        ],
        [
            'choiceTitle'               => 'Activate Multi-Step Forms',
            'instructionText'           => 'Use Multi-Step Forms',
            'icon'                      => 'list',
            'helpLink'                  => SCC_HELPDESK_LINKS['feature-multi-step-form'],
            'key'                       => 'activate-multiple-step',
            'evaluateAsDoneConditions'  => [ 'calculator.multi_step_enabled' ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'Form Conversion Analytics',
            'instructionText'           => 'Learn More About Form Conversion Analytics',
            'key'                       => 'form-conversion-analytics',
            'icon'                      => 'show_chart',
            'isDetectable'              => false,
            'helpLink'                  => SCC_HELPDESK_LINKS['feature-form-conversion-analytics'],
            'evaluateAsDoneConditions'  => [ 'calculator.visited_quote_management_screen' ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'Lead Source Analytics',
            'instructionText'           => 'Learn How to Use Lead Source Analytics',
            'key'                       => 'lead-source-analytics',
            'icon'                      => 'show_chart',
            'isDetectable'              => false,
            'helpLink'                  => SCC_HELPDESK_LINKS['feature-lead-source-analytics'],
            'evaluateAsDoneConditions'  => [ 'calculator.visited_quote_management_screen' ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'     => 'Quotes & Leads Dashboard',
            'instructionText' => 'Learn How to Use Quotes & Leads Dashboard',
            'key'             => 'quotes-n-leads-dashboard',
            'icon'            => 'assignment',
            'isDetectable'    => false,
            'helpLink'        => SCC_HELPDESK_LINKS['feature-leads-quotes-management'],
            'requiresPremium' => true,
        ],
    ],
    'elementSuggestions' => [
        [
            'choiceTitle'               => 'Dropdown',
            'instructionText'           => 'Create A Dropdown Menu',
            'helpLink'                  => SCC_HELPDESK_LINKS['element-dropdown'],
            'icon'                      => 'list',
            'key'                       => 'dropdown-element',
            'showSuggestion'            => false,
            'evaluateAsDoneConditions'  => [ 'calculator.element_dropdown' ],
            'requiresPremium'           => false,
        ],
        [
            'choiceTitle'               => 'Simple Buttons',
            'instructionText'           => 'Create Simple Buttons',
            'helpLink'                  => SCC_HELPDESK_LINKS['element-checkbox'],
            'icon'                      => 'smart_button',
            'key'                       => 'simple-buttons-element',
            'showSuggestion'            => false,
            'evaluateAsDoneConditions'  => [ 'calculator.element_simple_btns' ],
            'requiresPremium'           => false,
        ],
        [
            'choiceTitle'               => 'Checkbox',
            'instructionText'           => 'Create A Checkbox',
            'helpLink'                  => SCC_HELPDESK_LINKS['element-checkbox'],
            'icon'                      => 'check-square',
            'key'                       => 'checkbox-element',
            'showSuggestion'            => false,
            'evaluateAsDoneConditions'  => [ 'calculator.element_checkbox' ],
            'requiresPremium'           => false,
        ],
        [
            'choiceTitle'               => 'Comment Box',
            'instructionText'           => 'Create A Comment Box',
            'helpLink'                  => SCC_HELPDESK_LINKS['element-comment-box'],
            'icon'                      => 'message-circle',
            'key'                       => 'comment-box-element',
            'showSuggestion'            => false,
            'evaluateAsDoneConditions'  => [ 'calculator.element_comment_box' ],
            'requiresPremium'           => false,
        ],
        [
            'choiceTitle'               => 'Image Buttons',
            'instructionText'           => 'Create Image Buttons',
            'helpLink'                  => SCC_HELPDESK_LINKS['element-image-buttons'],
            'icon'                      => 'image',
            'key'                       => 'img-btn-element',
            'showSuggestion'            => true,
            'evaluateAsDoneConditions'  => [ 'calculator.element_image_btn' ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'Text/HTML Box With Conditional Logic Enabled',
            'instructionText'           => 'Create A Text/HTML Element With Conditional Logic Enabled',
            'choiceSimpleTitle'         => 'Text/HTML',
            'helpLink'                  => SCC_HELPDESK_LINKS['element-text-html-field'],
            'icon'                      => 'code',
            'key'                       => 'html-box-w-cl-element',
            'showSuggestion'            => false,
            'evaluateAsDoneConditions'  => [ 'calculator.element_texthtml_conditional_logic' ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'Quantity Box',
            'instructionText'           => 'Create A Quantity Box',
            'helpLink'                  => SCC_HELPDESK_LINKS['element-quantity-input-box'],
            'icon'                      => 'input-box',
            'key'                       => 'quantity-box-element',
            'showSuggestion'            => false,
            'evaluateAsDoneConditions'  => [ 'calculator.element_qtn_box' ],
            'requiresPremium'           => false,
        ],
        [
            'choiceTitle'               => 'Fee & Discount Adjuster',
            'instructionText'           => 'Create A Fee & Discount Adjuster',
            'helpLink'                  => SCC_HELPDESK_LINKS['element-custom-math'],
            'icon'                      => 'plus-square',
            'key'                       => 'custom-math-element',
            'showSuggestion'            => false,
            'evaluateAsDoneConditions'  => [ 'calculator.element_custom_math' ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'File Upload',
            'instructionText'           => 'Create A File Upload Field',
            'helpLink'                  => SCC_HELPDESK_LINKS['element-file-upload'],
            'icon'                      => 'paperclip',
            'key'                       => 'file-upload-element',
            'showSuggestion'            => false,
            'evaluateAsDoneConditions'  => [ 'calculator.element_file_upload' ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'TEXT/HTML',
            'instructionText'           => 'Create A TEXT/HTML Element',
            'helpLink'                  => SCC_HELPDESK_LINKS['element-text-html-field'],
            'icon'                      => 'type',
            'key'                       => 'text-html-element',
            'showSuggestion'            => false,
            'evaluateAsDoneConditions'  => [ 'calculator.element_texthtml' ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'Slider (with elements above it in the same subsection) (therefore, it will multiply the items and act a quantity modifier)',
            'instructionText'           => 'Create a slider in a subsection, with elements in the same subsection, the slider will multiply the items and act as a quantity modifier',
            'choiceSimpleTitle'         => 'Slider',
            'helpLink'                  => SCC_HELPDESK_LINKS['element-slider-all-types'],
            'icon'                      => 'sliders',
            'key'                       => 'slider-element',
            'showSuggestion'            => true,
            'evaluateAsDoneConditions'  => [ 'calculator.element_slider_with_the_subsection_having_other_element' ],
            'requiresPremium'           => false,
        ],
        [
            'choiceTitle'               => 'Slider With the Bulk Pricing or Sliding Scale Pricing Mode Turned On',
            'instructionText'           => 'Create A Slider With the Bulk Pricing or Sliding Scale Pricing Mode Turned On',
            'choiceSimpleTitle'         => 'Slider',
            'helpLink'                  => SCC_HELPDESK_LINKS['element-slider-all-types'],
            'icon'                      => 'sliders',
            'key'                       => 'slider-with-bulk-or-sliding-pricing-element',
            'evaluateAsDoneConditions'  => [ 'calculator.element_slider_with_bulk_sliding_mode' ],
            'requiresPremium'           => false,
        ],
        [
            'choiceTitle'               => 'Fee & Discount Adjuster With Conditional Logic trigger',
            'instructionText'           => 'Create \'A Fee & Discount Adjuster\' With Conditional Logic trigger',
            'choiceSimpleTitle'         => 'Fee & Discount Adjuster',
            'helpLink'                  => SCC_HELPDESK_LINKS['tutorial-master-guide-trigger-fee'],
            'icon'                      => 'plus-square',
            'key'                       => 'custom-math-with-cl-trigger-element',
            'evaluateAsDoneConditions'  => [ 'calculator.element_custom_math_with_custom_math_trigger' ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'Apply Mandatory Fees',
            'instructionText'           => 'Add mandatory fees with  element and a conditional logic trigger',
            'choiceSimpleTitle'         => 'Mandatory Fees',
            'helpLink'                  => SCC_HELPDESK_LINKS['tutorial-implementing-base-fee'],
            'icon'                      => 'plus-square',
            'key'                       => 'mandatory-fees',
            'evaluateAsDoneConditions'  => [ 'calculator.element_custom_math_with_mandatory_fees' ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'Apply A Percentage',
            'instructionText'           => 'Apply a percentage with the \'A Fee & Discount Adjuster\' element',
            'choiceSimpleTitle'         => 'Percentage',
            'helpLink'                  => SCC_HELPDESK_LINKS['tutorial-custom-percentage-addition'],
            'icon'                      => 'plus-square',
            'key'                       => 'need-to-apply-a-percentage',
            'evaluateAsDoneConditions'  => [ 'calculator.element_custom_math_with_percentage' ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'Calculate Shipping Fees',
            'instructionText'           => 'Use the Distance-based Calculations element to calculate shipping fees',
            'choiceSimpleTitle'         => 'Shipping Fees',
            'helpLink'                  => SCC_HELPDESK_LINKS['element-distance-cost'],
            'icon'                      => 'plus-square',
            'key'                       => 'shipping-rates-calculator',
            'evaluateAsDoneConditions'  => [ 'calculator.element_distance_based_calculations' ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'Image Buttons With Quantity Selector enabled',
            'instructionText'           => 'Use Image Buttons With Quantity Selector enabled',
            'choiceSimpleTitle'         => 'Image Buttons',
            'helpLink'                  => SCC_HELPDESK_LINKS['element-image-buttons'],
            'icon'                      => 'image',
            'key'                       => 'image-btn-w-qtn-sel-element',
            'evaluateAsDoneConditions'  => [ 'calculator.element_image_qtn_btn' ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'Advanced Pricing Formula',
            'instructionText'           => 'Use Advanced Pricing Formula to Create a Custom Calculation',
            'helpLink'                  => SCC_HELPDESK_LINKS['element-variable-math'],
            'icon'                      => 'sliders',
            'key'                       => 'variable-math-element',
            'evaluateAsDoneConditions'  => [ 'calculator.element_variable_math' ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'Date Picker',
            'instructionText'           => 'Create A Date Picker',
            'helpLink'                  => SCC_HELPDESK_LINKS['element-date-picker'],
            'icon'                      => 'calendar',
            'key'                       => 'date-picker-element',
            'showSuggestion'            => true,
            'evaluateAsDoneConditions'  => [ 'calculator.element_date_picker' ],
            'requiresPremium'           => true,
        ],
        [
            'choiceTitle'               => 'Distance-based Calculations',
            'instructionText'           => 'Calculate shipping fees with the Distance-based Calculations element',
            'helpLink'                  => SCC_HELPDESK_LINKS['element-distance-cost'],
            'icon'                      => 'map-pin',
            'key'                       => 'distance-element',
            'evaluateAsDoneConditions'  => [ 'calculator.element_distance_based_calculations' ],
            'requiresPremium'           => true,
        ],
    ],
] );

define( 'DF_SCC_TABLES', [
    0  => 'df_scc_conditions',
    1  => 'df_scc_coupons',
    2  => 'df_scc_elementitems',
    3  => 'df_scc_elements',
    4  => 'df_scc_forms',
    5  => 'df_scc_quote_submissions',
    6  => 'df_scc_sections',
    7  => 'df_scc_subsections',
  ] );
